C     MODULE            A  L  L  A  R  R           SUTRA VERISON 2D3D.1  ! terseq
C
C *** PURPOSE :
C ***  TO DECLARE THE MAIN ALLOCATABLE ARRAYS.
C
      MODULE ALLARR
      IMPLICIT NONE
      LOGICAL ALLO1, ALLO2, ALLO3          ! gm ALLO3
      DOUBLE PRECISION, DIMENSION(:,:), ALLOCATABLE ::
     1   PMAT, UMAT                                    
      DOUBLE PRECISION, DIMENSION(:), ALLOCATABLE ::
     1   PITER, UITER, PM1, DPDTITR, UM1, UM2, PVEL, SL, SR, X, Y, Z,
     2   VOL, POR, CS1, CS2, CS3, SW, DSWDP, RHO, SOP, QIN, UIN, QUIN,
     3   QINITR, RCIT, RCITM1               
      DOUBLE PRECISION, DIMENSION(:), ALLOCATABLE ::
     1   PVEC, UVEC                                        
      DOUBLE PRECISION, DIMENSION(:), ALLOCATABLE ::
     1   ALMAX, ALMIN, ATMAX, ATMIN, VMAG, VANG1,   
     2   PERMXX, PERMXY, PERMYX, PERMYY, PANGL1               
      DOUBLE PRECISION, DIMENSION(:), ALLOCATABLE ::
     1   ALMID, ATMID, VANG2, PERMXZ, PERMYZ,         
     2   PERMZX, PERMZY, PERMZZ, PANGL2, PANGL3               
      DOUBLE PRECISION, DIMENSION(:), ALLOCATABLE ::
     1   PBC, UBC, QPLITR                                
      DOUBLE PRECISION, DIMENSION(:,:), ALLOCATABLE ::
     1   GXSI, GETA, GZET                          
      DOUBLE PRECISION, DIMENSION(:), ALLOCATABLE ::
     1   FWK ,B                                            
      INTEGER, DIMENSION(:), ALLOCATABLE ::
     1   IN, IQSOP, IQSOU, IPBC, IUBC,                
     2   IOBS, NREG, LREG, NBI27, IWK, IA, JA
C
      END MODULE ALLARR
C
C     MODULE            P  T  R  D  E  F           SUTRA VERISON 2D3D.1  ! gm
C
C *** PURPOSE :
C ***  TO DEFINE POINTERS AND ARRAYS NEEDED TO CONSTRUCT THE
C ***  IA AND JA ARRAYS.
C
      MODULE PTRDEF
      IMPLICIT NONE
C.....DEFINE DERIVED TYPE LNKLST (LINKED LIST) WITH TWO COMPONENTS:      
C        NODNUM (NODE NUMBER) AND NENT (POINTER TO NEXT ENTRY).
      TYPE LNKLST                                                        
         INTEGER :: NODNUM                                               
         TYPE (LNKLST), POINTER :: NENT
      END TYPE LNKLST
C.....DECLARE DENT, DENTPV, DENTPI, AND DENTNW AS GENERAL-PURPOSE
C        POINTERS OF TYPE LNKLST.
      TYPE (LNKLST), POINTER :: DENT, DENTPV, DENTPI, DENTNW
C.....DEFINE DERIVED TYPE IPOINT WITH ONE COMPONENT: A POINTER, PL,
C        OF TYPE LNKLST.
      TYPE IPOINT
         TYPE (LNKLST), POINTER :: PL
      END TYPE IPOINT
C.....DECLARE HLIST, AN ARRAY OF POINTERS THAT WILL POINT TO THE HEAD
C        OF THE LINKED LIST OF NEIGHBORS FOR EACH NODE.
      TYPE (IPOINT), ALLOCATABLE :: HLIST(:)
C.....DECLARE ARRAY LLIST.
      INTEGER, DIMENSION(:), ALLOCATABLE :: LLIST
C
      END MODULE PTRDEF
